-- Universities in Bangladesh
-- Source: https://en.wikipedia.org/wiki/List_of_universities_in_Bangladesh
-- Run after schema.sql (table public.universities must exist).
-- Uses ON CONFLICT (slug) DO NOTHING so re-running is safe.

insert into public.universities (name, slug) values
  -- Public – General
  ('University of Dhaka', 'du'),
  ('University of Rajshahi', 'ru'),
  ('University of Chittagong', 'cu'),
  ('Jahangirnagar University', 'ju'),
  ('Islamic University, Bangladesh', 'iu'),
  ('Khulna University', 'ku'),
  ('Jagannath University', 'jnu'),
  ('Comilla University', 'cou'),
  ('Jatiya Kabi Kazi Nazrul Islam University', 'jkkniu'),
  ('Bangladesh University of Professionals', 'bup'),
  ('Begum Rokeya University', 'brur'),
  ('University of Barisal', 'bu'),
  ('Rabindra University, Bangladesh', 'rub'),
  ('Netrokona University', 'nku'),
  ('Kishoreganj University', 'kgu'),
  ('Meherpur University', 'mu'),
  ('Thakurgaon University', 'tu'),
  ('Naogaon University', 'ngu'),
  -- Public – Science and Technology
  ('Shahjalal University of Science and Technology', 'sust'),
  ('Hajee Mohammad Danesh Science and Technology University', 'hstu'),
  ('Mawlana Bhashani Science and Technology University', 'mbstu'),
  ('Patuakhali Science and Technology University', 'pstu'),
  ('Noakhali Science and Technology University', 'nstu'),
  ('Jashore University of Science and Technology', 'just'),
  ('Pabna University of Science and Technology', 'pust'),
  ('Gopalganj Science and Technology University', 'gstu'),
  ('Rangamati Science and Technology University', 'rmstu'),
  ('Jamalpur Science and Technology University', 'jstu'),
  ('Chandpur Science and Technology University', 'cstu'),
  ('Sunamganj Science and Technology University', 'sstu'),
  ('Bogura Science and Technology University', 'bstu'),
  ('Lakshmipur Science and Technology University', 'lstu'),
  ('Pirojpur Science and Technology University', 'prstu'),
  ('Satkhira University of Science and Technology', 'saust'),
  ('Narayanganj Science and Technology University', 'ngstu'),
  -- Public – Engineering
  ('Bangladesh University of Engineering and Technology', 'buet'),
  ('Military Institute of Science and Technology', 'mist'),
  ('Rajshahi University of Engineering and Technology', 'ruet'),
  ('Khulna University of Engineering and Technology', 'kuet'),
  ('Chittagong University of Engineering and Technology', 'cuet'),
  ('Dhaka University of Engineering and Technology', 'duet'),
  -- Public – Agricultural
  ('Bangladesh Agricultural University', 'bau'),
  ('Gazipur Agricultural University', 'gau'),
  ('Sher-e-Bangla Agricultural University', 'sbau'),
  ('Sylhet Agricultural University', 'sau'),
  ('Khulna Agricultural University', 'kau'),
  ('Habiganj Agricultural University', 'hau'),
  ('Kurigram Agricultural University', 'kuriau'),
  ('Shariatpur Agriculture University', 'shau'),
  -- Public – Medical
  ('Bangladesh Medical University', 'bmu'),
  ('Chittagong Medical University', 'cmu'),
  ('Rajshahi Medical University', 'rmu'),
  ('Sylhet Medical University', 'smu'),
  ('Khulna Medical University', 'kmu'),
  -- Public – Other specialized
  ('Chittagong Veterinary and Animal Sciences University', 'cvasu'),
  ('Bangladesh University of Textiles', 'butex'),
  ('Bangladesh Maritime University', 'bmu-maritime'),
  ('University of Frontier Technology, Bangladesh', 'uftb'),
  ('Aviation and Aerospace University Bangladesh', 'aaub'),
  -- Public – Off-campus
  ('National University, Bangladesh', 'nu'),
  ('Bangladesh Open University', 'bou'),
  ('Islamic Arabic University', 'iau'),
  ('Dhaka Central University', 'dcu'),
  -- International
  ('Islamic University of Technology', 'iut'),
  ('Asian University for Women', 'auw'),
  -- Private – General (selection; add more via admin if needed)
  ('North South University', 'nsu'),
  ('Independent University, Bangladesh', 'iub'),
  ('BRAC University', 'bracu'),
  ('American International University-Bangladesh', 'aiub'),
  ('East West University', 'ewu'),
  ('United International University', 'uiu'),
  ('Northern University Bangladesh', 'nub'),
  ('Stamford University Bangladesh', 'stamford'),
  ('Daffodil International University', 'daffodil'),
  ('Premier University, Chittagong', 'puc'),
  ('Southeast University', 'seu'),
  ('Green University of Bangladesh', 'green'),
  ('Leading University', 'lu'),
  ('Metropolitan University, Sylhet', 'metrouni'),
  ('Port City International University', 'pciu'),
  ('Varendra University', 'vu'),
  ('Bangladesh University', 'bu-bd'),
  ('BGC Trust University Bangladesh', 'bgctub'),
  ('Eastern University, Bangladesh', 'eu'),
  ('City University, Bangladesh', 'cub'),
  ('University of Asia Pacific', 'uap'),
  ('Asian University of Bangladesh', 'aub'),
  ('Primeasia University', 'primeasia'),
  ('Manarat International University', 'miu'),
  ('Southern University, Bangladesh', 'sub'),
  ('Sylhet International University', 'siu'),
  ('University of Development Alternative', 'uoda'),
  ('World University of Bangladesh', 'wub'),
  ('State University of Bangladesh', 'stateuniversity'),
  ('Royal University of Dhaka', 'rud'),
  ('Presidency University', 'presidency'),
  ('Victoria University of Bangladesh', 'vub'),
  ('Uttara University', 'uu'),
  ('Millennium University', 'millennium'),
  ('ASA University Bangladesh', 'asaub'),
  ('Bangladesh Islami University', 'biu'),
  ('East Delta University', 'edu'),
  ('European University of Bangladesh', 'eub'),
  ('Feni University', 'fu'),
  ('Khwaja Yunus Ali University', 'kyau'),
  ('North East University Bangladesh', 'neub'),
  ('North Western University, Bangladesh', 'nwu'),
  ('Sonargaon University', 'su'),
  ('Cox''s Bazar International University', 'cbiu'),
  ('Canadian University of Bangladesh', 'cub-can'),
  ('Global University Bangladesh', 'gub'),
  ('Grameen University', 'grameenu'),
  -- Private – Science and Technology
  ('University of Science and Technology Chittagong', 'ustc'),
  ('Ahsanullah University of Science and Technology', 'aust'),
  ('Bangladesh University of Business and Technology', 'bubt'),
  ('Atish Dipankar University of Science and Technology', 'adust'),
  ('Rajshahi Science and Technology University', 'rstu'),
  ('Central University of Science and Technology', 'cust'),
  -- Private – Specialized
  ('Central Women''s University', 'cwu'),
  ('University of Liberal Arts Bangladesh', 'ulab'),
  ('Bangladesh University of Health Sciences', 'buhs'),
  ('Bangladesh Army University of Engineering and Technology', 'bauet'),
  -- Catch-all for UPC results with unclear institution
  ('Other / Bangladesh (unclear)', 'other-bangladesh')
on conflict (slug) do nothing;
